### ISSUE TITLE
arcs not working

### ISSUE THREAD

**Issue by j-oakland** [robro/FitbitArcs#2]
Hello, 
I loaded your clockface Arcs on my fitbit two days ago.  The arcs are not active, the appearance is just the gray rings around the time and date.  The arcs do not appear as I progress through the day. I have checked permissions and reloaded the clockface.
Any suggestions?
Thanks!

**Comment by robro** [comment]
Thank you for letting me know. I experienced the same thing after a recent Fitbit update, but reloading the app through Fitbit Studio seemed to fix it. However, the version on the gallery is a bit older than this version on GitHub so that may have something to do with it.

I'll do some more testing, and if necessary I will submit the latest version to the Fitbit gallery, although it might take a few days because of the review process.

**Comment by j-oakland** [comment]
Ok, thank you for the response.  I'll look forward to the update...really
like this clockface design and interface!

**Comment by robro** [comment]
Well I figured out the problem. I wasn't explicitly defining "sweep-angle" in the style.css for the arcs, which meant that property defaulted to "undefined" and when the app tried to change it it threw a TypeError. I don't know why that used to work, but simply defining the property in the css file seems to have fixed things.

I will submit an updated version to the Fitbit gallery today.

**Comment by j-oakland** [comment]
That's great. Glad it was an easy fix.  Thank you so much!

**Comment by robro** [comment]
Fixed version has been submitted. I will close this when it goes live.

**Comment by j-oakland** [comment]
Ok. Thanks again

**Comment by robro** [comment]
Version 1.0.1 is now published on the Fitbit gallery. Thank you for liking my clock face and bringing this issue to my attention.
